ADMIN = "ADMIN"
SUPERADMIN = "SUPERADMIN"
GUEST = "GUEST"


USER_ROLES = (
    (ADMIN, ADMIN),
    (SUPERADMIN, SUPERADMIN),
    (GUEST, GUEST),
)
BULLET = "BULLET"
FOOD = "FOOD"
TRAVEL = "TRAVEL"
SPORT = "SPORT"

JOURNAL_TYPES = (
    (BULLET, BULLET),
    (FOOD, FOOD),
    (TRAVEL, TRAVEL),
    (SPORT, SPORT),
)